version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # Web console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434" # Ollama API port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432" # PostgreSQL default port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080" # Adminer web interface

volumes:
  minio_data:
  ollama_data:
  postgres_data:
