version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"  # Ollama API port
    volumes:
      - ollama_data:/root/.ollama

volumes:
  minio_data:
  ollama_data:
